name = "kubern-co"
compatibility_date = "2026-04-01"
pages_build_output_dir = "."

# ---------- Production ----------
[env.production]
[env.production.vars]
FROM_EMAIL = "hello@kubernco.com"
TO_EMAIL   = "jhudsongraves@gmail.com"

[[env.production.kv_namespaces]]
binding = "SUBMISSIONS"
id = "6d27e42f3bb74617862df12532db69c9"

# ---------- Preview ----------
[env.preview]
[env.preview.vars]
FROM_EMAIL = "hello@kubernco.com"
TO_EMAIL   = "jhudsongraves@gmail.com"

[[env.preview.kv_namespaces]]
binding = "SUBMISSIONS"
id = "46558ffe6570439da71508b03309efff"
